# Generated by Django 4.2.7 on 2023-11-27 09:45

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_projectcategory_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='color',
            field=models.CharField(default=accounts.utils.get_cat_color, max_length=20, null=True),
        ),
    ]
