# Generated by Django 4.2.7 on 2023-11-30 08:52

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=accounts.utils.get_avatar_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default=None, null=True, upload_to=accounts.utils.get_banner_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
