# Generated by Django 4.2.7 on 2023-11-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_avatar_alter_profile_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Статус'),
        ),
    ]
