# Generated by Django 4.2.7 on 2023-12-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_projectsfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectsFile',
            new_name='ProjectFile',
        ),
    ]
