# Generated by Django 4.2.7 on 2023-12-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_projectsfile_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название файла'),
        ),
    ]
